# Generated by Django 4.1.1 on 2023-07-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
